### ISSUE TITLE
Game unresponsive when generating new world

### ISSUE THREAD

**Issue by OcrSu** [Silverminer007/Shrines#11]
**Describe the bug**
Unresponsive when generating world

**To Reproduce**
1.New world options
2.World type: terraforge: bigbiome
3.Game mode: Creative
4.Start creating a new world
5.Progress 100%, game not responding

**Expected behavior**
Load the world normally, and the buildings generated by mod are also normal
**Screenshots**
no screanshot here
**Version (please complete the following information):**
 - OS: Win10 21H1 19043.1023
 - Forge Version forge-1.16.5-36.1.31
 - Java Version java11.0.10(64bit)
 - Mod Version Shrines-1.16.5-1.8.1-Beta3

**Additional context**
Here is my crashTXT
https://paste.ubuntu.com/p/3pycbrfGqG/

**Comment by Silverminer007** [comment]
Please tr yout with Beta4 and close this issue if it works now
