### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by thedeerirty** [Silverminer007/Shrines#13]
**Describe the bug**
Mass amount of server lag every few minutes

**To Reproduce**
Boot world with terraforged, dynamic trees, other structure mods like vahelsia, repurposed, etc. and then safetly remove.

**Expected behavior**
Simply generated structures, and then stopping future generation when removing

**Screenshots**
![error](https://user-images.githubusercontent.com/58305182/122857634-c8e9ab00-d2e6-11eb-9087-34110cde0866.PNG)

**Version (please complete the following information):**
 - OS: Windows
 - Forge Version 1.16.5-36.1.0
 - Mod Version 1.16.5-1.8.1

**Additional context**
I was using the mod in my modpack, to run a private server with some friends. Every few minutes, the server would rapidly save the configurartion for shrines, and when this happened, caused a large amount of lag to occur. In response, I thought I'd remove it, but foolishly didn't think this would also have errors. It now errors spam the console with what's above and causes more lag.

**Comment by Silverminer007** [comment]
Hi. 
The problem after removing this mod belongs to a mojang bug which isn't fixed up to now (I'm waiting for it the whole time). I've thought about adding different methods to correctly remove the mod, but no way worked.
Now to your problem. First of all, re-adding the mod will be likely to fix the logged bugs you've attached. I understand if you don't want to use this mod anymore, but you would need to create a new world to prevent this bugs without having this mod.
So, to prevent the legs from saving the config (What does it say in detail?), you could try to disable auto-save. You can find this setting in the "shrines.properties" file in the "shrines-saves" directory. If it still makes trouble on your server please come back to me so I can give more help.

**Comment by thedeerirty** [comment]
A new world makes sense; as for what it says, I can't exactly recall in detail, but it was Saving Config I believe, prefaced with like... [Shirnes] or [/Shrines] or somethin' like that. It spam it several times every 5-10 minutes.

I'll try reinstating it and see what it does

**Comment by Silverminer007** [comment]
I wan unable to fix this right now, but I was pointed to a workaround.
https://github.com/Nyveon/MCStructureCleaner
The python script removes all references to non existing structures which causes the game to stop saving and giving this output. I've never tried that out, because I had no time to do that, so you should take a look over it before running

**Comment by Silverminer007** [comment]
Moved this to new feature request, because it isn't a bug of this mod, but a bug this mod can solve
