### ISSUE TITLE
Too many saving config logs 

### ISSUE THREAD

**Issue by RuggedTime** [Silverminer007/Shrines#14]
As the title says, meaningless logs take too much space......Mod version 1.16.5 - 1.8.1
![image](https://user-images.githubusercontent.com/46664847/125753536-d95c7222-060d-401d-ac10-e296d5bec1c8.png)

**Comment by Silverminer007** [comment]
Thanks that you took the time to report. I've noticed that too and moved it to debug mode. Additionally there comes a  new option in the config that allows you to disable every logging that isn't a error message. Please be patient for replease of that update.

**Comment by RuggedTime** [comment]
Thanks! Looking forward to the new structures, they are so great.

**Comment by Silverminer007** [comment]
Please leave this open until the version is released. That helps me to remembr this in the case I need to remove it temporally for some reason.
There will be 2 new structures and many tecnical changes. The structues were build by an new structure builder. I hope you will enjoy them too. All the old (and also the ones who are still active) structure builder will love to hear that you like their structures

**Comment by NighthowlerStudios** [comment]
I assume just like When Dungeons Arise, that shifting to the vanilla Jigsaw system helped with performance?

**Comment by Silverminer007** [comment]
This is the wrong place for discussions like that. You can either open your own issue for questions, you join discord and ask there or you ask in the comments of the curseforge side, but please don't steal the threads of other people.
To answer your question: The change to jigsaw system was mainly to prevent bugs that occurred in other systems. More options and better performance are good things to take, but weren't the reason

**Comment by BeerCav** [comment]
Thank you for this thread.
