### ISSUE TITLE
Crash on launch with new beta  claiming "support for forge 36.2.0"

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#15]
you are incorrectly exporting compilation for the mod in beta 2.0.0 snapshot 6.  Please do not compile to Runtime 60, it must be Runtime 52 to retain backward compat to Java 8

"[02:30:50] [Render thread/ERROR]: Failed to load class com.silverminer.shrines.ShrinesMod
java.lang.UnsupportedClassVersionError: com/silverminer/shrines/ShrinesMod has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

**Comment by Silverminer007** [comment]
Thanks for reporting. I'll take a look on that and then upload a new file

**Comment by Silverminer007** [comment]
SNAPSHOT 7 works to me. Could you Test too? If it's fixed please close this issue

**Comment by NighthowlerStudios** [comment]
Yep, fully functional here.  Thanks.
