### ISSUE TITLE
Unable to control registry of structures into modded dimensions

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#17]
SNAPSHOT 8

You can't disable the structures from spawning in ANY dimension.  The log shows it still registers all Overworld ones in dimensions like Deep Dark, Undergarden, Atum etc, regardless.  :/

**Comment by NighthowlerStudios** [comment]
Note: easiest way to test this is to change the config for the Nether Pyramid to only spawn in the nether.  It will still spawn in the overworld regardless.

**Comment by NighthowlerStudios** [comment]
Originally I thought it was only modded dimensions but seeing that pyramid still show up even with my configs confirms to me it's registering shrines to all dimensions regardless.

**Comment by Silverminer007** [comment]
Thank you for the updates. You should try to delete the shrines-server.toml file in the serverconfig folder in the world folder or create a new world after making changes on config, because the world holds a own copy of the config so changes aren't updated. Could you make a new after you've tried that?

**Comment by NighthowlerStudios** [comment]
Somehow, some way, for whatever dumb reason, your config file was randomly reset.  I found that the dimension array was in fact still in tact. I'm gonna edit it again and see if that fixes it.

**Comment by NighthowlerStudios** [comment]
However, the log file does still show them as "registering"
 
is it running those methods and just applying nothing to those dimensions anyway?  I'm confused.

**Comment by Silverminer007** [comment]
I'm confused too ...Could you send the log file to me?Should we switch to discord?

**Comment by NighthowlerStudios** [comment]
turns out they're still generating in the overworld in general.  have you made any progress in figuring out a system to lock them to a specific dimension via config?

**Comment by Silverminer007** [comment]
I did a quick test, but when I disable the pyramid in the overworld so it can only spawn in the nether, they only spawn in the nether and not in the overworld. Maybe this is a mod compatibility issue. You're testing with your mod pack, right?

**Comment by NighthowlerStudios** [comment]
yes.

**Comment by Silverminer007** [comment]
I installed https://www.curseforge.com/minecraft/modpacks/kaleidios-battle-pack and tested it again. I tested it with the Nether Pyramid. I set the button to open the Shrines settings to 'k' and opened the menu. Here I went to the 'Included Structures' package and selected the Nether Pyramid. Here I went into the settings for the dimensions and deactivated the overworld. After restarting the game, the Nether pyramid only appeared in the Nether. Do you get a different result with the same procedure?

**Comment by NighthowlerStudios** [comment]
originally I disabled it by editing the toml manually.  I guess that is somehow broken?  I will try doing it with your menu system now.

**Comment by Silverminer007** [comment]
The Toml isn't used anymore. The config is now stored in a different way that isn't that easy to change manually

**Comment by NighthowlerStudios** [comment]
where is its location?  I need to export the configuration via modpacks

**Comment by Silverminer007** [comment]
The configuration files are saved in the structure packets, which are in 'shrines-saves' in your game directory

**Comment by NighthowlerStudios** [comment]
alright, thanks

**Comment by NighthowlerStudios** [comment]
![2021-11-06_18 13 15](https://user-images.githubusercontent.com/82226641/140619689-f0a44ad4-3d8e-41db-942d-11a7ac25134e.png)
as you can see here, your toggles are broken, when you click it by accident on the same toggle as previous toggle.

instead of removing the result when you turn it off, it does nothing, and when you toggle them on, it reads them regardless of if it was already there

that is why I had the config removed from controls last time

**Comment by Silverminer007** [comment]
![Bildschirmfoto von 2021-11-06 19-18-49](https://user-images.githubusercontent.com/66484505/140619845-14d31fd7-a22a-4e4b-bc4c-8c061810df46.png)
It works on my machine ...

**Comment by NighthowlerStudios** [comment]
well it definitely broke for me.  I think I clicked it several times on accident thinking it was gonna toggle when it didn't

**Comment by NighthowlerStudios** [comment]
anyways I was able to disable the pyramid, but accidentally the temple in the process

can you send me that config so I can fix my pack's?

**Comment by NighthowlerStudios** [comment]
I'll close this issue afterward

**Comment by Silverminer007** [comment]
Oh yeah. The buttons are broken. You need to press them on the currently not selected side

**Comment by Silverminer007** [comment]
What exactly do you want me to send you?

**Comment by NighthowlerStudios** [comment]
the nbt file of the config you just made that has those nether structures only registered to the nether

**Comment by NighthowlerStudios** [comment]
I need it so I can repair mine as I accidentally deleted mine's pyramid.

**Comment by Silverminer007** [comment]
You can delete the whole packet and it will recover it self after the game was restarted, but I'll send you the file on discord, because GitHub doesn't allow nbt uploads here

**Comment by NighthowlerStudios** [comment]
alright, thanks.  do fix that gui tho!
