### ISSUE TITLE
Harbor spawn problem

### ISSUE THREAD

**Issue by GauntAndreX8** [Silverminer007/Shrines#19]
**Describe the bug**
When the harbor spawn it caused to lower some of the water do you think it can be fixed

**To Reproduce**

**Expected behavior**

**Screenshots**
![2021-09-12_16 20 47](https://user-images.githubusercontent.com/85809443/133006119-a01d7e63-433e-4605-96b7-82ba19e64b2a.png)
![2021-09-12_16 19 47](https://user-images.githubusercontent.com/85809443/133006120-7414dd4b-5c65-4f07-b5c5-3fdb0fce6c92.png)

**Version (please complete the following information):**
 - OS: [Windows]
 - Forge Version [e.g. 1.16.5-36.2.0]
 - Mod Version [e.g. 1.16.5-2.0.0 SNAPSHOT 10]

**Additional context**

**Comment by Silverminer007** [comment]
It's not a hard one, but it's a lot of work, so I hope you understand it's going to take some time to fix it

**Comment by GauntAndreX8** [comment]
ok sure i will be patient thxs
