### ISSUE TITLE
Shrine structures will cut a big hole in the bedrock

### ISSUE THREAD

**Issue by Mr-Syntax** [Silverminer007/Shrines#21]
i found out that it is because shrines automatically rolled itself back to version 1.8.1?

very weird issue, but the new version works just fine

it was with this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Silverminer007** [comment]
In the latest version of the modpack there seems to be the alpha version of the shrine mod. On which version was the old version 1.8.1?

**Comment by Silverminer007** [comment]
I will mark this as fixed as the problem no longer occurs in the new version
