### ISSUE TITLE
Structures registered to a dimension with negative dimension ID will spawn in overworld as well regardless of config

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#23]
2.0.0-beta4

fresh config.

able to easily find the End Temple in the Overworld

**Comment by Silverminer007** [comment]
What do you mean with 'negative dimension ID'? I thought I would use string dimension IDs, am I wrong?

**Comment by NighthowlerStudios** [comment]
The end's dimension ID is -1 (internal index).  your end dimension structures are spawning in the overworld.

**Comment by NighthowlerStudios** [comment]
I'm sure that if I add the end tag to a different structure, it will start appearing in the overworld too because of this.

**Comment by Silverminer007** [comment]
Thank you. I'm gonna try that

**Comment by NighthowlerStudios** [comment]
it might be a completely different reason on the backend but yeah, adding the end tag will let it spawn in the overworld regardless if overworld is on or not.

**Comment by Silverminer007** [comment]
Sorry for the long delay. I've tried to reproduce the issue and followed the following steps:
- Download the Mod on version 2.0.0-beta4
- Create a new forge installation with version 36.2.19
- Started Minecraft with just Shrines
- Create a new world with default settings, but create with gamemode creative
- Open shrines novels screen by pressing 'k'
- Open advanced mode
- Edit default structures packet
- Edit shrines:abandoned_witch_house
- configure dimension whitelist
- Add minecraft:the_end
- remove minecraft:overworld
- Exit the GUI and restart Minecraft
- Open the same world
- Locate shrines:abandoned_witch_house in the Overworld
- Log says 'Could not find that structure nearby'

At which step does your procedure differ? Could you give such an detailed list of steps to allow me to reproduce your issue?

**Comment by NighthowlerStudios** [comment]
Mine differs on "edit shrines:abandoned_witch_house". the one I keep trying to edit is "end_temple"

then i try to configure dimension whitelist, removing the overworld from the default list and keeping the end only.

removing that does not function, the end temple still keeps generating in the overworld

**Comment by NighthowlerStudios** [comment]
the log will still say "could not find that structure nearby" but the temple is still there :/ even on a fresh world with the new settings
