### ISSUE TITLE
Crashing on world creation

### ISSUE THREAD

**Issue by lebagvondouche** [Silverminer007/Shrines#24]
**Describe the bug**
Crashing on world creation with my own modpack, works if I disable the mod.

**To Reproduce**
1. Use my modpack I guess, not sure if this is a problem with the Forge version or not.

**Expected behavior**
World created as usual.

**Version (please complete the following information):**
 - OS: Windows
 - Forge Version 1.16.5-32.6.8
 - Mod Version 1.8.1 and 2.0.0

**Additional context**
Crashlog: https://pastebin.com/A43weBU9

**Comment by Silverminer007** [comment]
Does the error also affect 2.0.0? In the given log file you have used 1.8.1

**Comment by lebagvondouche** [comment]
Yeah I tried with 2.0.0 as well same error, sorry for the confusion.

Crashlog for 2.0.0: https://pastebin.com/M9qW3X0D

**Comment by Silverminer007** [comment]
Sorry for the delay. I'm unable to reproduce your issue. I've followed the following steps:
- Downloads version 1.0.4 of your modpack on curseforge
- Imported the modpack in MultiMc
- Changed Forge version to 36.2.20
- Started Minecraft
- Created a mew world with default settings
- Located shrines:ballon

Everything worked just fine. Could you give a process description like this? Does the issue still persist on latest versions?

**Comment by Silverminer007** [comment]
I close this issue because of inactivity. Please reopen this issue and give an up to date overview if the issue wasn't resolved before
