### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by Cocklet** [Silverminer007/Shrines#3]
Can you please make it so we can spawn it in any biome or show us how. I never see the structures and then i came across a plains biome and saw like all of them. I do have modded biomes and would like the structures to spawn in those as well

**Comment by Silverminer007** [comment]
Use the shrines-server.toml config to change the Biomes. It uses Biome Categories, so your modded biomes should be able to be added over this. I know the problem, that the structures generate such close to each other and i'm still working on it.

`[structures.small_tempel]
		#Biome Types the Small Tempel can generate in
		biome_categories = ["PLAINS", "FOREST", "TAIGA", "JUNGLE", "SWAMP", "EXTREME_HILLS", "MESA", "SAVANNA", "ICY", "DESERT", "MUSHROOM"]`

This is a part of the config file. In the Brackets is a List of every biome(without OCEAN, BEACH and RIVER). If you add this list in your config to every structure, you will make them appear in every biome, also your modded ones should be matched. With the next release are more Biome Categories matched by default, so you could also wait 2 days for this.

**Comment by Cocklet** [comment]
okay thanks
