### ISSUE TITLE
[1.18.1] Keybind not Respected

### ISSUE THREAD

**Issue by itsdinkd** [Silverminer007/Shrines#30]
The bug here is that when changing the key bind for shrines GUI to something like CTRL+K instead of `k` pressing K still opens up the menu, with or without pressing `ctrl`.

**Comment by Silverminer007** [comment]
Fixed for 3.0.0 in next release. I'm gonna fix that for 2.0.0 later

**Comment by Silverminer007** [comment]
1.16.5 fix is released, 1.18 version will still take a while, because it comes with a huger bunch of changes which needs to be tested

**Comment by Silverminer007** [comment]
Fixed in Beta5 for 1.18
