### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by Omnimetatron** [Silverminer007/Shrines#32]
**Describe the bug**
Server crashes on load. Unfortunately a bug report isn't generated, so I can't include one.

**To Reproduce**
Load forge server with latest version of Shrines

**Expected behavior**
Server to load.

**Screenshots**

**Version (please complete the following information):**
 - OS: Win 11
 - Forge Version 1.18.1-39.0.17
 - Mod Version 3.0.0-Beta5

**Additional context**
Client loaded just fine, only server appears to be affected. Unfortunately a crash report isn't generated, so I can't include one.

**Comment by Silverminer007** [comment]
Please upload the lastest.log to a pastesite like pastebin or GitHub gist

**Comment by Silverminer007** [comment]
Please confirm fix in Beta 6

**Comment by Silverminer007** [comment]
Since I have not received any further replies, I am closing this issue. If the problem persists, you can open this issue again
