### ISSUE TITLE
Server Crash after update.

### ISSUE THREAD

**Issue by mtebrinke** [Silverminer007/Shrines#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Forge Version [e.g. 1.16.5-36.1.0]
 - Mod Version [e.g. 1.16.5-1.7.1]

**Additional context**

**Comment by mtebrinke** [comment]
https://mcpaste.io/4cb6e13870f9393d

**Comment by mtebrinke** [comment]
This was for Forge 1.18.1 (sorry my host is truncating it.

The crash was for Shrines-1.18.1.3.0.0.0Beta5

When I went back to Beta4 it loads fine.

**Comment by Silverminer007** [comment]
Please confirm fix in Beta 6

**Comment by mtebrinke** [comment]
Thank you!
