### ISSUE TITLE
Crash updating from Beta 17 to Beta 20

### ISSUE THREAD

**Issue by evhub** [Silverminer007/Shrines#40]
**Describe the bug**

When updating from Shrines 1.18.1 3.0.0 Beta17 to Shrines 1.18.1 3.0.0 Beta20 build3 (and I can confirm on Beta19 as well), the server crashes on startup. See log here: https://gist.github.com/evhub/37820b84919c8cd15ddb96977a7c26b1

**Version (please complete the following information):**
 - OS: Windows 10
 - Forge Version: 1.18.1 39.1.2
 - Mod Version: 1.18.1 3.0.0 Beta20 build3

**Comment by Silverminer007** [comment]
You're missing shrines new required dependency, dynamic registries. You can download it from curseforge, GitHub or modrinth. Closing
