### ISSUE TITLE
Big Structure Spawns way too often and not correctly

### ISSUE THREAD

**Issue by SHXRKIEgg** [Silverminer007/Shrines#41]
**Describe the bug**
Big Structure Spawns way too often and not correctly

**To Reproduce**
Use latest 1.18.2 Version

**Expected behavior**
Not generate inconsistently in bad places where it looks out of place

**Screenshots**
![image](https://user-images.githubusercontent.com/79353591/161481650-dd41773a-414c-4ec0-bdfb-2ddd785dded2.png)
![image](https://user-images.githubusercontent.com/79353591/161481639-1f7678c3-9b80-4573-aeaa-1c362e02ed34.png)
![image](https://user-images.githubusercontent.com/79353591/161481941-2cad0305-783d-48c1-9449-cf99b09500f6.png)

**Version (please complete the following information):**
 - OS: Windows 10
 - Forge Version Forge 40.0.36
 - Mod Version Shrines-1.18.2-4.0.0-alpha2.jar

**Additional context**
This is also happening to a lot of other structures I believe and will their ever be a config to disable some structures?
I also assume this is cause its in Alpha and will be fixed eventually?

**Comment by Silverminer007** [comment]
Thank you for the report. That is a known issue. My plan is to re-introduce a minimum amount of chunks between two structures. Alpha 3 targeted the harbour already you showed. The curseforge upload for that version failed, but you can get it from GitHub at the moment. In theory you can disable structures with datapacks, but I know that isn't the most comfortable way. I'm open for suggestions about a better way. You can take a look at the readme here on GitHub to get an idea about my current plans. If you have any further suggestions just let me know

**Comment by Silverminer007** [comment]
The harbour issues are solved since alpha 7 and in alpha 10, there is the option to enforce a minimum distance between two structure. Therefore, I'll close this issue, as all topics are resolved. Feel free to reopen this issue or open a new issue if there is still a bug.
