### ISSUE TITLE
Harbour not spawing correctly

### ISSUE THREAD

**Issue by asodugf12** [Silverminer007/Shrines#42]
Harbour is behaving very weirdly
It is spawning on canyons, small lakes, etc
This is the most absurd one I have seen
![Screenshot (275)](https://user-images.githubusercontent.com/91423016/163678563-55150cfa-47cb-498a-abad-f97eeb1535b7.png)
Version: 1.18.2
Mod version: 4.0.0 alpha 2
OS: Windows 11

**Comment by Silverminer007** [comment]
I guess you're using the 1.18.2 alphas. Could you try to update to alpha 5 and reproduce?

**Comment by asodugf12** [comment]
I cant find alpha 5 tho
can u help me pls?

**Comment by asodugf12** [comment]
I cant seem to open minecraft with alpha 5
here's the crash log
ill look into it further
[crash-2022-04-16_21.36.03-fml.txt](https://github.com/Silverminer007/Shrines/files/8500098/crash-2022-04-16_21.36.03-fml.txt)

**Comment by Silverminer007** [comment]
You should try to update forge. Alpha 5 requires Forge 40.0.36 or above

**Comment by asodugf12** [comment]
oh thanks

**Comment by Silverminer007** [comment]
Close as fixed
