### ISSUE TITLE
Shrines-1.18.2-4.0.0-beta4.jar Crash

### ISSUE THREAD

**Issue by Reshy** [Silverminer007/Shrines#43]
**Describe the bug**
Crash on load with Shrines-1.18.2-4.0.0-beta4.jar

**Version (please complete the following information):**
 - OS: Windows 10
 - Forge Version 40.1.20
 - Mod Version Shrines-1.18.2-4.0.0-beta4.jar

**Additional context**
https://pastebin.com/c33rvXs0 Crash Log.

**Comment by Silverminer007** [comment]
As the change log states, shrines 1.18.2-4.0.0-beta4 and above require Forge 40.1.35 or above
