### ISSUE TITLE
Mod cannot load (registry error)

### ISSUE THREAD

**Issue by apugo** [Silverminer007/Shrines#44]
When trying to load Minecraft with the mod installed, I get the message: 

Shrines (shrines) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'net.minecraftforge.registries.RegistryBuilder net.minecraftforge.registries.RegistryBuilder.dataPackRegistry(com.mojang.serialization.Codec)'

This is with version Shrines-1.18.2-4.0.0.jar.

**Comment by Silverminer007** [comment]
Shrines for 1.18.2 requires Forge 40.1.35 or above. Please update your Forge version and it will work again
