### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by KleiczeK** [Silverminer007/Shrines#45]
![image](https://user-images.githubusercontent.com/107305203/173185281-acbb18ab-f0f9-4704-8dd4-cfbddbb24b5e.png)
idk how to repair it

**Comment by Silverminer007** [comment]
See #44 & #43. You have to update Forge to 40.1.35 or above

**Comment by Silverminer007** [comment]
Please leave this issue open, so others can see how to fix this issue
