### ISSUE TITLE
Possible TerraForged conflict

### ISSUE THREAD

**Issue by HueyKablooey** [Silverminer007/Shrines#5]
I added this mod to an existing game and the game crashes whenever I enter a new area and the game tries to spawn one of your structures. The disabled the first structure that caused the crash (Mineral Shrine) and the next one (balloon) crashed as well. Seems to be an issue with your mod and TerraForged world gen. Crash report is as follows

[crash-2021-03-27_16.27.04-client.txt](https://github.com/Silverminer007/Shrines/files/6216371/crash-2021-03-27_16.27.04-client.txt)

**Comment by HueyKablooey** [comment]
TerraForged developer said it isn't hard to make structures compatible with his world gen.

https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

**Comment by Silverminer007** [comment]
You are using version 1.7.0-Beta2. In 1.7.0-Beta3 it should be fixed, but in version 1.7.0-Beta4 I've changed somethings because of this, so i'll add the "fixed in next release" label. Does it still occures in version 1.7.0-Beta3?

**Comment by Silverminer007** [comment]
Fixed in last commit
