### ISSUE TITLE
"Mod shrines is shipping outdated structure files, which can cause worldgen lag"

### ISSUE THREAD

**Issue by Reshy** [Silverminer007/Shrines#51]
[29May2023 08:05:27.358] [Worker-Main-4/WARN] [ModernFix/]: Mod shrines is shipping outdated structure files, which can cause worldgen lag; please report this to them.

Not sure if this is an issue, but it showed up in my logs during testing.  There was also a gap in the world that occurred.  Might be related.

**Comment by Silverminer007** [comment]
I need more context for this to fix. Which version are you using? Which Minecraft version? What did you use to test this? Which other mods are installed? A screenshot of the gap would be nice

**Comment by Reshy** [comment]
This is for Shrines-1.18.2-4.1.0.jar
