### ISSUE TITLE
[1.18.2] Using an unique eye from End Remastered causes a crash with this mod

### ISSUE THREAD

**Issue by Catomax262** [Silverminer007/Shrines#52]
**Describe the bug**
Using End Remastered's new eyes will crash the game due to this mod skipping the generation of the End Remastered end portal. (I suppose)

**To Reproduce**
1. Craft or obtain any End Remastered eyes
2. Try to locate a stronghold by using any of them
3. Crash

**Expected behavior**
To not crash and let me find the stronghold.

**Screenshots**

**Version (please complete the following information):**
 - OS: Windows
 - Forge Version: 40.2.5
 - Mod Version: 4.1.0

**Additional context**
Crash report: https://crashy.net/0dff233a-717c-4e7b-8601-a87421a6412c

**Comment by Silverminer007** [comment]
Have you tested this in a setup with all mods installed, but not Shrines? Did it crash too? Does it also happen if you have only End Remastered and Shrines installed?

Considering the crashlog, it looks more like it's a issue on End Remastered's side, where they're missing a dependency or something
