### ISSUE TITLE
[Request] Compatibility with Lootr

### ISSUE THREAD

**Issue by faeldray** [Silverminer007/Shrines#7]
Lootr changes chests so that they are instanced per player. That way on servers, players don't have to explore as far just to find random loot. It would be great if Shrines was compatible with this.

https://www.curseforge.com/minecraft/mc-mods/lootr/

**Comment by Silverminer007** [comment]
I see your point. I'm working on it. Hopefully tomorrow i'm done, but you may have to wait some more time up to the next release

**Comment by faeldray** [comment]
Sounds fine, thanks for working on it!

**Comment by Silverminer007** [comment]
So now I'm done. See branch 'test'.

I'll let this open until the new version with the fix is released

Could you test it when it's released?

**Comment by faeldray** [comment]
Sure thing :)

**Comment by Silverminer007** [comment]
So the new version (1.8.0) should now be compactible with lootr. Could you test and in the case, that it works, close this issue?
![2021-05-15_12 35 30](https://user-images.githubusercontent.com/66484505/118360026-240cdd00-b586-11eb-9960-435fa0f6e8d3.png)

**Comment by faeldray** [comment]
I used the /locate command to find all the structures and sure enough, they all had Lootr chests/barrels. Except the water shrine I think it's called, but I don't know if that ever generates with loot.

Anyways, thanks so much! I'll go ahead and close the issue.
