### ISSUE TITLE
Shrines Structures Mod (v1.8.1-Beta3) Causing Start-Up Crashes on Minecraft 1.16.5 Servers (Forge 36.1.31)

### ISSUE THREAD

**Issue by MarioMario24680** [Silverminer007/Shrines#9]
**Describe the bug**
The server crashes immediately as soon as it begins loading Shrines Structures during the start-up phase.

**To Reproduce**
Create a Forge 36.1.31 server for Minecraft 1.16.5 and add the latest version of the Shrines Structures mod (version 1.8.1-Beta3) to the server's list of loaded mods.

**Expected behavior**
The server was expected to start up normally.

**Additional context**
An earlier version of this mod (version 1.8.1-Beta1) doesn't cause any issues, but trying the newest version results in this crash report: 
[crash-2021-06-10_19.11.20-fml.txt](https://github.com/Silverminer007/Shrines/files/6635001/crash-2021-06-10_19.11.20-fml.txt)

**Comment by Silverminer007** [comment]
Please tr yout with Beta4 and close this issue if it works now

**Comment by MarioMario24680** [comment]
Thanks a lot, the latest version Beta4 works fine now on servers.
